
keepers = [
    "Freddie Freeman",
    "Carlos Correa",
    "Kyle Tucker",
    "Gerrit Cole",
    "Kevin Gausman",
    "Ozzie Albies",
    "Shohei Ohtani",
    "Ronald Acuña Jr.",
    "Walker Buehler",
    "Max Fried",
    "Ketel Marte",
    "Aaron Judge",
    "Bryan Reynolds",
    "Mike Trout",
    "Max Scherzer",
    "Zack Wheeler",
    "Vladimir Guerrero Jr.",
    "Rafael Devers",
    "Xander Bogaerts",
    "Trevor Story",
    "Mookie Betts",
    "Nick Castellanos",
    "Cody Bellinger",
    "Robbie Ray",
    "José Ramírez",
    "Trea Turner",
    "Bryce Harper",
    "Shane Bieber",
    "Brandon Woodruff",
    "Bo Bichette",
    "Juan Soto",
    "Fernando Tatis Jr.",
    "Jacob deGrom",
    "Lucas Giolito",
    "Pete Alonso",
    "Marcus Semien",
    "Corey Seager",
    "Corbin Burnes",
    "Aaron Nola"
]
